version: "3.8"
services:
  python:
    build: .
    restart: always
    working_dir: /
    entrypoint: python3 -m ptvsd --host 0.0.0.0 --port 5678 --wait -m src.main
    volumes:
      - ./src:/src
    ports:
      - 5678:5678
